jiaoyu/apps/courses/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from jiaoyu.settings import MEDIA_ROOT,MEDIA_URL
from .views import CourseListView,CourseDetailView,CourseInfoView


urlpatterns = [
    url(r'^course_list/$',CourseListView.as_view(),name='course_list'),
    url(r'^course_detail/(?P<course_id>.*)/$',CourseDetailView.as_view(),name='course_detail'),
    url(r'^course_info/(?P<course_id>.*)/$',CourseInfoView.as_view(),name='course_info '),

]+static(MEDIA_URL,document_root=MEDIA_ROOT)

jiaoyu/apps/organizations/urls.py
from django.conf.urls import url,include
from organizations.views import OrgList,UserAskFormView,OrgHomeView,OrgCourseView,OrgDescView,OrgTeacherView,UserFavView,TeacherListView,TeacherDetailView
from django.conf.urls.static import static
from jiaoyu.settings import MEDIA_ROOT,MEDIA_URL

urlpatterns = [
    url(r'^org_list/$',OrgList.as_view(),name="org_list"),
    url(r'^user_ask/$',UserAskFormView.as_view(),name='user_ask'),
    url(r'^org_home/(?P<org_id>.*)/$',OrgHomeView.as_view(),name='org_home'),
    url(r'^org_course/(?P<org_id>.*)/$',OrgCourseView.as_view(),name='org_course'),
    url(r'^org_desc/(?P<org_id>.*)/$',OrgDescView.as_view(),name='org_desc'),
    url(r'^org_teacher/(?P<org_id>.*)/$', OrgTeacherView.as_view(), name='org_teacher'),
    url(r'^add_fav/$',UserFavView.as_view(),name='add_fav'),
    url(r'^teacher_list/$',TeacherListView.as_view(),name='teacher_list'),
    url(r'^teacher_detail/(?P<teacher_id>.*)/$',TeacherDetailView.as_view(),name='teacher_detail'),
]+static(MEDIA_URL,document_root=MEDIA_ROOT)

jiaoyu/jiaoyu/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import xadmin
from django.views.generic import TemplateView
from users.views import user_login,user_register,active_user,forget_pwd,reset_pwd,modify_pwd
from organizations.views import OrgList
from django.conf.urls.static import static
from jiaoyu.settings import MEDIA_ROOT,MEDIA_URL
urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$',TemplateView.as_view(template_name='index.html'),name='index'),
    url(r'^userlogin$',user_login.as_view(),name='userlogin'),
    url(r'^register/$',user_register.as_view(),name='register'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$',active_user.as_view(),name='active'),
    url(r'^forgetpwd/$',forget_pwd.as_view(),name='forget'),
    url(r'^reset/(?P<reset_code>.*)/$',reset_pwd.as_view(),name='reset'),
    url(r'^modify/$',modify_pwd.as_view(),name='modify'),
    url(r'^org/',include('organizations.urls',namespace='org')),
    url(r'^course/',include('courses.urls',namespace='course')),
]+static(MEDIA_URL,document_root=MEDIA_ROOT)

jiaoyu/apps/courses/models.py
from datetime import  datetime
from django.db import models
from organizations.models import CourseOrg,Teacher
# Create your models here.


class Course(models.Model):
    name = models.CharField(max_length=50,verbose_name="课程名字")
    desc = models.CharField(max_length=200,verbose_name="课程描述")
    detail = models.TextField(verbose_name="课程详情")
    degree = models.CharField(max_length=5,choices = (('cj',"初级"),('gj',"高级"),('zj',"中级")),verbose_name="课程难度",default='cj')
    courtime = models.IntegerField(default=0,verbose_name="课程时长")
    teacher = models.ForeignKey(Teacher,verbose_name='教师',null=True,blank=True)
    click_nums = models.IntegerField(default=0,verbose_name="点击次数")
    course_org = models.ForeignKey(CourseOrg,null=True,blank=True,verbose_name="课程机构")
    fav_nums = models.IntegerField(default=0,verbose_name="收藏此书")
    category = models.CharField(max_length=20,verbose_name="课程类别",default="后台开发")
    image = models.ImageField(upload_to="courses/%Y/%m",verbose_name="课程封面")
    studys = models.IntegerField(default=0,verbose_name="学习人数")
    tag = models.CharField(max_length=40,verbose_name="课程标签",default="服务操作系统")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="登记时间")
    tonggao = models.CharField(default='',max_length=100,verbose_name='课程公告')
    youneed_know = models.CharField(max_length=200,default='',verbose_name='课程须知')
    teacher_tell = models.CharField(max_length=200, default='', verbose_name='老师告诉你学到什么')
    class Meta:
        verbose_name = "课程详情"
        verbose_name_plural = verbose_name

    def get_lesson_nums(self):
        return self.lesson_set.all().count()

    def get_users(self):
        return self.usercourse_set.all()

    def get_lesson(self):
        return self.lesson_set.all()
    def get_resource(self):
        return self.courseresource_set.all()


    def __str__(self):
        return  self.name


class Lesson(models.Model):
    name = models.CharField(max_length=50,verbose_name="章节名")
    course = models.ForeignKey(Course,verbose_name="属于课程")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="登记时间")

    class Meta:
        verbose_name = "章节详情"
        verbose_name_plural = verbose_name
    def get_video(self):
        return self.video_set.all()

    def __str__(self):
        return self.name


class Video(models.Model):
    name = models.CharField(max_length=50,verbose_name="视频名称")
    lesson = models.ForeignKey(Lesson,verbose_name="对应章节")
    videourl = models.CharField(default='',max_length=100,verbose_name='视频地址')
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    class Meta:
        verbose_name = "视频信息"
        verbose_name_plural = verbose_name

    def  __str__(self):
        return  self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course,verbose_name="对应课程")
    name = models.CharField(max_length=50,verbose_name="资源名称")
    file = models.FileField(upload_to="courses/resource/%Y/%m",verbose_name="文件")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    class Meta:
        verbose_name = "课程资源"
        verbose_name_plural = verbose_name

    def __str__(self):
        return  self.name

jiaoyu/apps/users/forms.py
from django import forms
from captcha.fields import CaptchaField



class Login_form(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True,min_length=5,error_messages={'invalid':'不能少于5位'})


class Register_form(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True,min_length=5)
    captcha = CaptchaField()


class ForgetPwd_form(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField()

class Reset_form(forms.Form):
    password1 = forms.CharField(required=True, min_length=5)
    password2 = forms.CharField(required=True, min_length=5)

jiaoyu/extra_app/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

jiaoyu/templates/course-detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
在线教育平台之课程详情
{% endblock %}
{% block custom_bread %}
<section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="index.html">首页</a>></li>
                <li><a href="course-list.html">公开课程</a>></li>
				<li>课程详情</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}
{% block content %}
    <section>
	<div class="wp">
		<div class="groupPurchase_detail detail">
			<div class="toppro">
				<div class="left">
					<div class="picbox">
						<div class="tb-booth tb-pic">
							<img width="440" height="445" src="{{ MEDIA_URL }}{{ course.image }}" class="jqzoom" />
						</div>

					</div>
					<div class="des">
						<h1 title="django 从入门到精通体验开始了">{{ course.name }}</h1>
						<span class="key">{{ course.desc }}</span>
						<div class="prize">
							<span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
							<span class="fr">学习人数：{{ course.studys }}</span>
						</div>
						<ul class="parameter">
							<li><span class="pram word3">时&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;长：</span><span>{{ course.courtime }}</span></li>
                            <li><span class="pram word3">章&nbsp;节&nbsp;数：</span><span>{{ course.get_lesson_nums }}</span></li>
                            <li><span class="pram word3">课程类别：</span><span title="">{{ course.category }}</span></li>
							<li class="piclist"><span class="pram word4">学习用户：</span>
                                {% for cuser in course.get_users %}
                                <span class="pic"><img width="40" height="40" src="{{ MEDIA_URL }}{{ cuser.user.image }}"/></span>
                                {% endfor %}

							</li>
						</ul>
						<div class="btns">
							<div class="btn colectgroupbtn"  id="jsLeftBtn">
                                  {% if has_course_fav %}已收藏{% else %}收藏{% endif %}
                            </div>
                                <div class="buy btn"><a style="color: white" href="{% url 'course:course_info ' course.id%}">开始学习</a></div>
						</div>
					</div>
                    <div class="group-share-box">
                        <div class="bdsharebuttonbox"
                             data-text="django开始了"
                             data-desc="我在#慕课网#发现了"
                             data-comment=""
                             data-url="/group/groupdetail/15/">
                            <span class="fl">分享到：</span>
                            <a href="#" class="bds_more" data-cmd="more"></a>
                            <a title="分享到QQ空间" href="#" class="bds_qzone" data-cmd="qzone"></a>
                            <a title="分享到新浪微博" href="#" class="bds_tsina" data-cmd="tsina"></a>
                            <a title="分享到腾讯微博" href="#" class="bds_tqq" data-cmd="tqq"></a>
                            <a title="分享到人人网" href="#" class="bds_renren" data-cmd="renren"></a>
                            <a title="分享到微信" href="#" class="bds_weixin" data-cmd="weixin"></a>
                        </div>
                    </div>
				</div>
				<div class="right">
					<div class="head">
						<h1>授课机构</h1>
						<p>世界名校，课程权威</p>
					</div>
					<div class="pic">
                        <a href="/company/14/">
                            <img width="150" height="80" src="{{ MEDIA_URL }}{{ course.course_org.image }}"/>
                        </a>
                    </div>
					<a href="/company/14/">
                        <h2 class="center" title="清华大学">{{ course.course_org.name }}</h2>
                    </a>
					<div class="btn  notlogin
					     "data-favid="14" id="jsRightBtn">
                         {% if has_org_fav %}已收藏{% else %}收藏{% endif %}
                    </div>
					<div class="clear">
						<ul>
                            <li>
                                <span>课 &nbsp;程&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   {{ course.course_org.courses }}</span>
                            </li>
                            <li>
                                <span>教 &nbsp;师&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  {{ course.course_org.get_teacher_nums }}</span>
                            </li>
							<li>所在地区：&nbsp;&nbsp;{{ course.course_org.address }}</li>
							<li>认&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;证&nbsp;:
                                &nbsp;&nbsp;
								    <img title="金牌机构", src="{% static 'images/gold.png' %}"/>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
    <section>
	<div class="wp">
		<div class="list groupPurchase_detail_pro">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="active">课程详情</li>
					</ul>
                    {{ course.detail }}
				</div>
				<div class="tab_cont tab_cont2" >
					<div class="comment">
						<div class="comenlist">

	                    </div>
					</div>
				</div>
			</div>
			<div class="right layout">
				<div class="head">相关课程推荐</div>
                <div class="group_recommend">
                    {% for tcourse in tcourses %}
                     <dl>
                            <dt>
                                <a target="_blank" href="">
                                    <img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ tcourse.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <a target="_blank" href=""><h2> {{ tcourse.name }}</h2></a>
                                <span class="fl">学习时长：<i class="key">{{ tcourse.courtime }}</i></span>
                            </dd>
                        </dl>
                    {% endfor %}
                </div>
			</div>
		</div>
	</div>
</section>
    {% block custom_js %}
    <script type="text/javascript">
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url 'org:add_fav' %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="login.html";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('#jsLeftBtn').on('click', function(){
    add_fav($(this), {{ course.id }}, 1);
});

$('#jsRightBtn').on('click', function(){
    add_fav($(this), {{ course.course_org.id }}, 2);
});


</script>
    {% endblock %}
{% endblock %}

jiaoyu/templates/course-video.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
公开课视频信息--
{% endblock %}
{% block custom_css %}
   <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
     <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
{% endblock %}
{% block custom_bread %}
<section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
				<li><a href="{% url 'course:course_detail' course.id %}">课程详情</a>></li>
                <li>章节信息</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}
{% block content %}
<div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.courtime }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.studys }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="course-video.html"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href=""><span>评论</span></a></li>
                    </ul>
                </div>
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">{{ course.tonggao }}</a> </div>
                </div>

                <div class="mod-chapters">
                    {% for lesson in course.get_lesson %}
                    <div class="chapter chapter-active" >
                        <h3>
                            <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                        </h3>
                        <ul class="video">
                            {% for video in lesson.get_video %}
                             <li>
                                <a target="_blank" href='{{ MEDIA_URL }}{{ video.videourl }}' class="J-media-item studyvideo">{{ video.name }} (0)
                                    <i class="study-state"></i>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endfor %}

                </div>

            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                        {% for resource in course.get_resource %}
                         <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ resource.file }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                        {% endfor %}

                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                            <span class="job">{{ course.teacher.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.youneed_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_tell }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">
                                {% for relate_course in relate_courses %}
                                <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="{{ MEDIA_URL }}{{ relate_course.image }}" alt="{{ relate_course.name  }}">
                                            <span class="name autowrap">{{ relate_course.name  }}</span>
                                        </a>
                                    </li>
                                {% endfor %}

                                </ul>
                            </div>
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                <ul class="other-list">
                                    <li class="curr">
                                        <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                            <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                            <span class="name autowrap">Java工程师</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>    </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>
{% endblock %}